Repository merdekainfotek/merdekainfotek, pull requests merged in 2023-08, with the labels that each got.

#1 Update: styles and content
  src/app/globals.css
  src/components/layouts/Footer.tsx
Labels: documentation, enhancement

#16 PR: update landing page
  src/app/page.tsx
Labels: enhancement

#19 PR: fix broken links at navigation to pages
  src/app/about/page.tsx
  src/app/contact/page.tsx
  src/app/service/page.tsx
  src/components/layouts/Footer.tsx
  src/components/layouts/NavBarDesktop.tsx
Labels: bug

#28 PR: check
  src/components/layouts/Header.tsx
  src/components/layouts/NavBarMobile.tsx
Labels: enhancement

#31 Add services page
  src/app/service/page.tsx
  src/components/cards/ServiceCard.tsx
Labels: enhancement

#30 PR: review
  src/app/about/page.tsx
  src/app/contact/page.tsx
  src/app/page.tsx
  src/components/layouts/Footer.tsx
  src/components/layouts/Header.tsx
  src/components/layouts/NavBarMobile.tsx
Labels: enhancement

#46 install emailjs package
  package-lock.json
  package.json
  src/app/contact/page.tsx
Labels: enhancement

#52 adjustment some breakpoints
  tailwind.config.ts
Labels: enhancement

#55 PR: review
  src/app/about/page.tsx
  src/app/contact/page.tsx
  src/app/globals.css
  src/app/page.tsx
  src/app/service/page.tsx
  src/components/cards/ServiceCard.tsx
  src/components/layouts/NavBarDesktop.tsx
  src/components/layouts/NavBarMobile.tsx
Labels: bug

#57 Secure emailjs API keys
  src/app/contact/page.tsx
Labels: enhancement

#59 PR: review
  src/app/service/fullstack/page.tsx
  src/app/service/page.tsx
  src/app/service/webdev/page.tsx
  src/components/cards/ServiceCard.tsx
  src/constant/index.ts
  src/types/index.ts
Labels: enhancement

#65 PR: review color changes
  src/app/about/page.tsx
  src/app/contact/page.tsx
  src/app/globals.css
  src/components/MissionVision.tsx
  src/components/cards/TeamCard.tsx
Labels: enhancement

#68 Feat: content for webdev page
  src/app/service/webdev/page.tsx
Labels: enhancement
